<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net48;net8.0</TargetFrameworks>

		<!-- NuGet package metadata -->
		<PackageId>Wifi.Toolbox</PackageId>
		<Version>1.0.0</Version>
		<Authors>Nicolas Waldner</Authors>
		<Description>A awesome library with tools for use in Console applications</Description>
		<PackageTags>utilities;framework48</PackageTags>
		<RepositoryUrl>https://github.com/nicolaswaldner/sw_developer_2025_nicolas/tree/develop/20251211/Wifi.Toolbox</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>

		<!-- Optional: if you keep AssemblyInfo.cs -->
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Title>WIFI Toolbox</Title>
		<PackageProjectUrl>https://github.com/nicolaswaldner/sw_developer_2025_nicolas/tree/develop/20251211/Wifi.Toolbox</PackageProjectUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageIcon>Logo.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\readme.md" Pack="true" PackagePath="\" />
		<None Include="Logo.png" Pack="true" PackagePath="" />
	</ItemGroup>
</Project>

